sudo: required

language: python

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

services:
  - docker

before_install:
  - chmod +x tests/helloworld/build.sh

script:
  - whereis firefox
  - tests/helloworld/build.sh
  - python tests/helloworld/test.py