sudo: required

language: python

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

services:
  - docker

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.21.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin
  - chmod +x tests/helloworld/build.sh
  - chmod +x Authentication/tests/build.sh
  - chmod +x Web/tests/build.sh
  - pip install -r tests/helloworld/requirements.txt

script:
  - whereis firefox
  - tests/helloworld/build.sh
  - python tests/helloworld/test.py
  - Authentication/tests/build.sh
  - sleep 10
  - python Authentication/tests/test.py
  - Web/tests/build.sh
  - python Web/tests/test.py