version: '3'
services:
  webserver1:
    build:
      context: ./Web/WebServer/
    container_name: webserver1
    networks:
     - skitter

  webserver2:
    build:
      context: ./Web/Webserver/
    container_name: webserver2
    networks:
     - skitter

  loadbalancer:
    build:
      context: ./Web/Loadbalancer
    ports:
      - "80:80"
    networks:
      - skitter

    locust-master:
    build:
      context: ./Web/LoadTesting/
      dockerfile: Dockerfile
    volumes:
      - ./LoadTesting/scripts:/scripts
    ports:
      - "8089:8089"
    networks:
      - skitter

  locust-worker:
    build:
      context: ./Web/LoadTesting/
      dockerfile: Dockerfile
    command: "--master-host=locust-master"
    volumes:
      - ./LoadTesting/scripts:/scripts
    networks:
      - skitter

  auth_app:
    build:
      context: ./Authentication
    container_name: authserver
    ports:
      - "8080:8080"
    networks:
      - skitter

networks:
  skitter:
    driver: bridge
