version: '3'
services:
  webserver1:
    build:
      context: ./Web/WebServer/
    container_name: skitterwebserver1
    networks:
     - skitter

  webserver2:
    build:
      context: ./Web/Webserver/
    container_name: skitterwebserver2
    networks:
     - skitter

  loadbalancer:
    build:
      context: ./Web/Loadbalancer
    container_name: skitterloadbalancer
    ports:
      - "80:80"
    networks:
      - skitter

  locust-master:
    build:
      context: ./Web/LoadTesting/
    container_name: skitterlocustmaster
    volumes:
      - ./LoadTesting/scripts:/scripts
    ports:
      - "8089:8089"
    networks:
      - skitter

  locust-worker:
    build:
      context: ./Web/LoadTesting/
    container_name: skitterlocustworker
    command: "--master-host=locust-master"
    volumes:
      - ./LoadTesting/scripts:/scripts
    networks:
      - skitter

  auth_app:
    build:
      context: ./Authentication
    container_name: skitterauthserver
    ports:
      - "8080:8080"
    networks:
      - skitter

  database:
    image: mariadb:latest
    container_name: skitteruserdb
    volumes:
      - ./Database/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ./Database/userdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=skitteradmin
      - MYSQL_DATABASE=skitter

networks:
  skitter:
    driver: bridge
