version: '3'
services:
  webserver1:
    build:
      context: ./Web/WebServer/
    container_name: skitterwebserver1
    networks:
     - skitter

  webserver2:
    build:
      context: ./Web/WebServer/
    container_name: skitterwebserver2
    networks:
     - skitter

  loadbalancer:
    build:
      context: ./Web/LoadBalancer
    container_name: skitterloadbalancer
    ports:
      - "80:80"
    networks:
      - skitter

  locust-master:
    build:
      context: ./Web/LoadTesting/
    container_name: skitterlocustmaster
    volumes:
      - ./LoadTesting/scripts:/scripts
    ports:
      - "8089:8089"
    networks:
      - skitter

  locust-worker:
    build:
      context: ./Web/LoadTesting/
    container_name: skitterlocustworker
    command: "--master-host=locust-master"
    volumes:
      - ./LoadTesting/scripts:/scripts
    networks:
      - skitter

  auth_app:
    build:
      context: ./Authentication
    container_name: skitterauthserver
    ports:
      - "8080:8080"
    networks:
      - skitter

  database:
    image: mariadb:latest
    container_name: skitteruserdb
    volumes:
      - ./Database/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ./Database/userdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=skitteradmin
      - MYSQL_DATABASE=skitter

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: skitterelastic
    environment:
      - cluster.name=skitter
      - "ES_JAVA_OPTS=-Xms1G -Xms1G"
    ports:
      - 9200:9200
    networks:
      - skitter
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144


networks:
  skitter:
    driver: bridge
