version: '3'
services:
  auth_app:
    build:
      context: ./Authentication
    container_name: skitter/auth_server
    ports:
      - "8080:8080"
    networks:
      - skitter

networks:
  skitters:
    driver: bridge