package auth;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import auth.User;
import auth.UserRepository;

@RestController
public class HomeController {
    @Autowired  // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/")
    public String index() {
        return "Welcome to the home page!";
    }

    @GetMapping(path="/createUser")
    public String registerUser(@RequestParam String name, @RequestParam String email, @RequestParam String password) {

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setPassword(password);    // TODO Replace with hashing, once I figure out how that works here
        
        userRepository.save(n);
        return "Registered successfully?";
    }
}
