version: '3'
services:
  auth_app:
    build:
      context: .
    container_name: skitterTests/authServer
    ports:
      - "8080:8080"
    networks:
      - auth

networks:
  auth:
    driver: bridge
